export const GOOGLE_CONFIG = {
    // GOOGLE GENERAL
    CLIENT_ID: import.meta.env.VITE_GOOGLE_CLIENT_ID,
    REDIRECT_URI: import.meta.env.VITE_GOOGLE_REDIRECT_URI,
    SCOPE: import.meta.env.VITE_GOOGLE_SCOPE,

    // GOOGLE DRIVE COTIZACIONES 
    COTIZACIONES_ROOT_FOLDER_ID: import.meta.env.VITE_GOOGLE_COTIZACIONES_ROOT_FOLDER_ID,

    // GOOGLE SHEETS ENTRADAS-SALIDAS
    ENTRADAS_SALIDAS_SPREADSHEET_ID: import.meta.env.VITE_GOOGLE_ENTRADAS_SALIDAS_SPREADSHEET_ID,
};